### ISSUE TITLE
NULL error causes program end

### ISSUE THREAD

**Issue by ruthdouglas** [iandouglas96/pwr#2]
I don't know why the program stopped running, but this is what I see
at the end of the data stream sometime this afternoon:
....
Getting Power...
power data received: 0.409
PV pwr: 0.409 kW
C:\Users\ruthdouglasmiller\pwr\sma.js:40
        var retval = NULL;
                     ^

ReferenceError: NULL is not defined
    at Socket.<anonymous> (C:\Users\ruthdouglasmiller\pwr\sma.js:40:22)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:619:8)

**Comment by iandouglas96** [comment]
This should be resolved, try the latest commit.
