### ISSUE TITLE
"index out of range" error

### ISSUE THREAD

**Issue by ruthdouglas** [iandouglas96/pwr#3]
After running all night, at 9:12am index thru this error and the program stopped running:

Getting Power...
power data received: 1.996
PV pwr: 1.996 kW
Getting Power...
buffer.js:970
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:970:11)
    at Buffer.readUInt32LE (buffer.js:1032:5)
    at Socket.<anonymous> (C:\Users\ruthdouglasmiller\pwr\sma.js:33:28)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:619:8)

**Comment by iandouglas96** [comment]
TODO: improve handling of stray messages from inverter.
